name: senecabot
description: A discord bot that gives you quotes from Seneca The Younger! made in Dart
version: 1.0.0
# repository: https://github.com/lovzay/senecabot

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  nyxx: ^6.1.0
  nyxx_commands: ^6.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
